using MCSharp.Cmds;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MCSharp.Test
{
    internal class Test
    {
        public static void Main(string[] args)
        {
            Datapack.name = "qwq";  //数据包名字
            Datapack.discription = "A datapack generated by MCSharp";   //数据包描述
            Datapack.outputPath = "D:\\.minecraft\\saves\\Datapack Lab\\datapacks";   //数据包路径
            Datapack.outputPath = ".\\";   //数据包路径
            start();    //功能的入口
            //Commands.Say("qwq");      不能直接在主函数中使用命令
            Datapack.Create();      //生成数据包
        }

        public static void start()
        {
            //一个函数
            Datapack.RegistryFunction();    //注册此函数为命令函数，可以在函数中使用命令
            Commands.Say("start!");
            test1();
            test2();    //函数的调用
        }

        public static void test1()
        {
            Datapack.RegistryFunction();
            Commands.Say("test1");
            test2();    //函数的调用
        }

        public static void test2()
        {
            Datapack.RegistryFunction();
            Commands.Say("test2");
        }
    }
}
