using MCSharp.Cmds;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MCSharp.Test
{
    internal class Test
    {
        public static void Main(string[] args)
        {
            Datapack.name = "qwq";  //数据包名字
            Datapack.discription = "A datapack generated by MCSharp";   //数据包描述
            Datapack.outputPath = "D:\\.minecraft\\saves\\Datapack Lab\\datapacks";   //数据包路径
            start();        //一个功能
            //Datapack.PrintFunctionNames();
            Datapack.Create();      //生成数据包
            //Console.ReadKey();
        }

        public static void start()
        {
            Datapack.RegistryFunction();
            test(); //嵌套函数调用
            test2();
            Commands.Say("startfun end");
        }

        public static void test()
        {
            Datapack.RegistryFunction();
            Commands.Say("qwq");
            test2();
        }

        public static void test2()
        {
            Datapack.RegistryFunction();
            Commands.Say("awa");
        }
    }
}
