using MCsharp;
using MCsharp.Commands;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MCSharp.Test
{
    internal class Test
    {
        public static void Main(string[] args)
        {
            Datapack.name = "qwq";  //数据包名字
            Datapack.discription = "A datapack generated by MCSharp";   //数据包描述
            Datapack.outputPath = "D:\\.minecraft\\saves\\Datapack Lab\\datapacks";   //数据包路径
            Commands.Say("Hello World");    //命令/say
            Datapack.Create();      //生成数据包
        }
    }
}
